"""empty message

Revision ID: a4b41e3153a9
Revises: f075250f511a
Create Date: 2022-06-04 08:33:38.333261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4b41e3153a9'
down_revision = 'f075250f511a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.drop_constraint('show_Artist_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'])
    op.drop_column('show', 'time')
    op.drop_column('show', 'Artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('Artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('show', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_Artist_id_fkey', 'show', 'artist', ['Artist_id'], ['id'])
    op.drop_column('show', 'artist_id')
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
